title: Daniel May

url: "danielmamay.github.io"

style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji
  - jekyll-feed
  - jekyll-sitemap

permalink: /:year/:month/:day/:title/

include: ['_pages']

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

google_analytics_key: UA-155063782-1

social_media:
  twitter: danielmamay
